linters:
  default: none
  enable:
    - gocognit
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - nakedret

linters-settings:
  gocyclo:
    min-complexity: 30
  gocognit:
    min-complexity: 30
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/sipeed/picoclaw
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30

run:
  timeout: 30m
  skip-dirs:
    - vendor
    - web/frontend
    - scratch
    - pkg/channels
    - pkg/audio
    - cmd/picoclaw-launcher-tui
    - web/backend/api
  tests: false
  skip-files:
    - .*_test.go